# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('univ', models.CharField(help_text='Full Name을 적어 주세요. (ex)서울대학교)', max_length=20, verbose_name='대학교')),
                ('major', models.CharField(help_text='Full Name을 적어 주세요. (ex)기계항공공학)', max_length=20, verbose_name='전공')),
                ('group', models.CharField(choices=[('Tue', '화요일조'), ('Wed', '수요일조'), ('Thu', '목요일조'), ('Fri', '금요일조')], max_length=20, verbose_name='요일조')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
