# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(max_length=20, verbose_name='요일조'),
        ),
    ]
